# Generated by Django 5.1.7 on 2025-12-11 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='passage_id',
            field=models.CharField(help_text='Passage ID', max_length=255, verbose_name='passage_id'),
        ),
    ]
